#5 install paru

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,15 +1,16 @@
 #!/usr/bin/env sh
 
-# The directory of this repository
-current_directory=$(CDPATH= cd -- "$( dirname -- "$0")" && pwd)
+echo "Finding path to this repo..."
+current_directory=$(cd -- "$( dirname -- "$0")" > /dev/null 2>&1 && pwd)
+echo "Repo detected at ${current_directory}"
 
-# Do a full system upgrade before starting the install script
 echo "Doing a full system upgrade before starting the installation..."
 sudo pacman -Syyu
 
-# Install packages required to run this script
-required_packages="${CDIR}/etc/required.txt"
+echo "Installing packages required to run the install script..."
+required_packages="${current_directory}/etc/required.txt"
 if [ -s "$required_packages" ]; then
+    # shellcheck disable=SC2024
     sudo pacman -S --needed - < "$required_packages"
 fi
 
@@ -19,25 +20,36 @@ XDG_CACHE_HOME="${HOME}/.cache"
 XDG_DATA_HOME="${HOME}/.local/share"
 XDG_STATE_HOME="${HOME}/.local/state"
 
-# Create important directories
-echo "Creating directories according to the XDG Base Directory Specification"
+echo "Creating directories according to the XDG Base Directory Specification..."
 mkdir -vp "${XDG_CONFIG_HOME}"
 mkdir -vp "${XDG_CACHE_HOME}"
 mkdir -vp "${XDG_DATA_HOME}"
 mkdir -vp "${XDG_STATE_HOME}"
 
-echo "Creating directories necessary for the installation"
+echo "Creating directories necessary for the installation..."
 mkdir -vp "${HOME}/.local/bin"
-
-# Symlink files to their respective location under $HOME
 
 # Use stow to do most of this work
 echo "Symlinking files with stow..."
 stow --verbose=2 --dir "${current_directory}" --target "${HOME}"
 
-# Download paru (https://aur.archlinux.org/packages/paru) so packages from the AUR can be installed.
-# $current_directory/setup-scripts/paru.sh
-
 # sudo ln -sf $current_directory/etc/unlock-conservation-mode.service /etc/systemd/system/
 # sudo systemctl enable unlock-conservation-mode
+
+echo "Installing additional packages..."
+
+if ! (which paru > /dev/null 2>&1); then
+    echo "Installing paru from AUR..."
+    if (
+        git clone https://aur.archlinux.org/paru.git
+        cd paru || exit
+        makepkg -si --clean
+        cd ..
+        rm -rf paru
+    ); then
+        echo "Failed to install paru" >&2
+    fi
+else
+    echo "paru already installed, skipping..."
+fi
 
